package common;

public enum MethodType {
    TRAVELTOAIPORT,
    WAITINQUEUE,
    SHOWDOCUMENTS,
    WAITINGTOBECHECKEDIN,
    BOARDPLANE,
    WAITFORPLANETOLAND,
    LEAVEPLANE,
    LEAVEAIRPORT,
    INFORMREADYFORBOARDING,
    WAITINGFORBOARDING,
    ANNOUNCEARRIVAL,
    WAITINGFORDEBOARDING,
    WAITINGFORNEXTFLIGHT,
    WAITINGFORPASSENGER,
    ASKFORDOCUMENTS,
    WAITINGTOCHECKPASSENGER,
    INFORMREADYTOFLY,
    ISINFORMPILOTTOCEASEACTIVITY,
    INFORMPLANEISNOLONGERNEEDED,
}
